#pragma once

void ui_test_begin();
void ui_test_end();
void ui_test_set_scroll_offset();
void ui_test_smooth_scroll();
void ui_test_push_window_to_front();
void ui_test_push_window_to_back();
void ui_test_generate_id();
void ui_test_dock_node_create_();
void ui_test_dock_node_create();
void ui_test_dock_node_create_multiple_windows();
void ui_test_dock_node_set_split();
void ui_test_dock_node_resize_traverse();
void ui_test_dock_node_dock_window();
void ui_test_dock_node_resize_from_root();
void ui_test_find_node();
void ui_test_dock_node_remove_node();
void ui_test_set_docking();
void ui_test_display_docking();
void ui_test_remove_window_from_shared_dock_space();
void ui_test_look_for_window_resize();
void ui_test_set_resize_cursor();
void ui_test_check_window_collisions();
void ui_test_check_if_window_should_be_docked();
void ui_test_check_dock_space_resize();
void ui_test_sync_current_frame_windows();
void ui_test_handle_tab_change_or_close();
void ui_test_ui_window_close();
